---
- name: Playbook to generate changelogs
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    image_registry: "ip-172-31-5-165.eu-west-2.compute.internal:5000/ocp4/openshift4:"
    container_image: 
      - 4.4.4-jenkins
      - 4.4.4-grafana
  tasks:
    - include_tasks: task.yml
      with_items: "{{ container_image }}"
      loop_control:
        loop_var: container_image
